# Generated by Django 3.0.3 on 2020-02-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('size_x', models.IntegerField(default=0)),
                ('size_y', models.IntegerField(default=0)),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='entities.EntityType')),
                ('uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
