CELL_SIZE = 62 * 3
EXIT_HEIGHT = 8
EXIT_WIDTH = CELL_SIZE / 2
MAP_MARGIN_X = 5
MAP_MARGIN_Y = 5
CELL_BORDER = 1

COLOR_RENDER_BG = (0, 0, 0)
COLOR_LOCATION_BG = (100, 100, 100)
COLOR_EXIT_ACCESSIBLE = COLOR_LOCATION_BG
COLOR_EXIT_INACCESSIBLE = COLOR_RENDER_BG


FOG_OF_WAR = False
